### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by kal2944** [kal2944/Catalog_of_my_things#1]
### **Hello Reviewer*
- We will do this project in a group of 3 people
Team member 1: Kalkidan Daniel @kal2944 
Team member 2: Fitz Gerald @fitz95 
Team member 3: Muhammad Huzaifa khan @huzaifakhan0308
- We have set up the Kanban board
The kanban project [link](https://github.com/kal2944/Catalog_of_my_things/projects/1)
- We did a Descriptive title and description of the task for each card

**Comment by BenMukebo** [comment]
### Hi @fitz95, @kal2944,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- Descriptive ISSUES.  ✔️ 
- Your Kanban board is a based on the provided template board. 🥇 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] Great job adding cards to the kanban board 👏🏻 However  each card on the board  should have:
  - Descriptive title.
  - The number of points in the \[Xpt\] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of work.
  - A description of the task.

- [ ] Please makes sure all cards are assigned to team members. Each card should have a circle with user's avatar.

![image](https://user-images.githubusercontent.com/79058364/234002808-58029073-fa6a-4820-a081-25ff20a5de1d.png)

- [ ] Here is project requirements. Let's make sure: 
  - All requirements listed as [group tasks](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md#group-task:~:text=Group%20task,quit%20the%20app.)  should have a corresponding card in the Kanban board.
  - All requirements from the list for a given student in the [project requirements divided by team member ](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) file should have a corresponding card in the Kanban board.
  - You should have significantly (difference >= 5 points) more or less points than others

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kal2944** [comment]
Fixed

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @fitz95, @kal2944 and @huzaifakhan0308,

✔️ Tasks are properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
